### ISSUE TITLE
Missing libclang.so

### ISSUE THREAD

**Issue by remram44** [tomaka/rustc-emscripten#3]
Building `emscripten-sys` fails:
```
error: failed to run custom build command for `emscripten-sys v0.3.2`
process didn't exit successfully: `/src/target/release/build/emscripten-sys-55f5ae5b24c31eac/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.1\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', /checkout/src/libcore/result.rs:916:5
```

**Comment by zombiezen** [comment]
I'm hitting this too, and can also reproduce outside of container.  Perhaps this is an issue with emscripten-sys?

**Comment by remram44** [comment]
I reported it upstream and trzeci/emscripten:sdk-incoming-64bit works now. Should be just a matter of rebuilding the rustc-emscripten image.

cf https://github.com/asRIA/emscripten-docker/pull/25

**Comment by tomaka** [comment]
~~Note that this repo is not maintained at all!
I don't know if anything is still in the working state but I'd recommend not using it even if that's the case.~~

EDIT: Wait, nevermind!

**Comment by remram44** [comment]
I see! Thanks for letting us know nonetheless! [`trzeci/emscripten`](https://github.com/asRIA/emscripten-docker) has been working great for my use.

**Comment by tomaka** [comment]
Wait, sorry! I screwed up! I thought I was in a different repo!
This repo is definitely maintained!

The `rustc-emscripten` image is supposed to rebuild automatically whenever the upstream image is updated, so it should be up-to-date now.
