### ISSUE TITLE
Missing `emcc`?

### ISSUE THREAD

**Issue by goddessfreya** [tomaka/rustc-emscripten#5]
Hey, 

Around 16 days ago our circleci builds have started failing, see https://circleci.com/gh/tomaka/glutin/3000?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Does this have anything to do with #4 ? I'm no good with these devops things and would be grateful if you point me to the right direction.

**Comment by tomaka** [comment]
Well, I'm going to revert #4 and create a different image.

**Comment by goddessfreya** [comment]
This has fixed it, thanks.
